services:
  - type: web
    name: economic-energy-trends
    env: static
    buildCommand: null
    staticPublishPath: ./
    routes:
      - type: rewrite
        source: /
        destination: /index.html